# Thin module so builder.py can read runtime UI flags without circular imports.
UI_FORCE_ORGANIC_GREEN  = True
UI_FORCE_EXOTIC_MAGENTA = True

INHERIT_MOON_AXIAL_TILT        = True
INHERIT_STAR_AXIAL_TILT        = False
ALIGN_ORBITS_TO_STAR_EQUATOR   = False
GENERATE_SURFACE_DATA = True
SURFACE_DATA_MODE = "full_us_like"
ATTACH_SURFACE_GRID_COMPONENT = True
ACTIVE_SURFACE_PHYSICS = False
SAFE_SURFACE_EXPORT_ICE_MASK = True
NORMALIZE_SE_ATMOSPHERE = False
NORMALIZE_SE_ATMOSPHERE_MODE = "off"
NORMALIZE_ATMOSPHERE_PRESERVE_TOTAL_PRESSURE = True
STRICT_ATMOSPHERE_MASS_CONSISTENCY = False
STRICT_CLOUD_COVERAGE_VALIDATION = False
ATMOSPHERE_READBACK_TOLERANCE = 0.20

# Imported atmosphere preservation
PRESERVE_SE_ATMOSPHERE_PRESSURE = True
STATIC_IMPORTED_ATMOSPHERES = False
SURFACE_GAS_PRESSURE_MODE = "off"
OCEAN_DEPOT_EXPORT_MODE = "legacy"
LOCK_IMPORTED_ATMOSPHERIC_DEPOTS = False
LOCK_IMPORTED_LIQUID_DEPOTS = False
CAP_SURFACE_WATER_DEPOT_FOR_STATIC_ATMOSPHERES = True
REMOVE_OCEAN_WATER_FROM_VOLATILE_DEPOTS_FOR_STATIC_ATMOSPHERES = True
MAX_STATIC_SURFACE_WATER_DEPOT_FRACTION_OF_ATMOSPHERE = 0.02
MAX_STATIC_SURFACE_OTHER_VOLATILE_FRACTION_OF_ATMOSPHERE = 0.001
EXPORT_FULL_OCEAN_MASS_AS_DEPOT = False
STATIC_ATMOSPHERE_DEPOT_MODE = "none"
# "none" | "carrier_unlocked" | "carrier_locked" | "chemical_unlocked" | "chemical_locked"
STATIC_ATMOSPHERE_CARRIER_DEFAULT = "Nitrogen"
STATIC_ATMOSPHERE_CARRIER_COLD = "Helium"
STATIC_IMPORTED_ATMOSPHERE_SURFACE_POLICY = "no_grid"
# "no_grid" | "passive_grid" | "active_legacy"

# Startup
START_PAUSED = True
START_SIMULATION_SPEED_REALTIME = True
DEFAULT_TIME_STEP_PER_REAL_SEC = 3600.0
DISABLE_AUTOSPEED_ON_EXPORT = False